// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SplittedSRAM_2(
  input         clock,
  input         reset,
  output        io_r_req_ready,
  input         io_r_req_valid,
  input  [8:0]  io_r_req_bits_setIdx,
  output [41:0] io_r_resp_data_0,
  output [41:0] io_r_resp_data_1,
  output [41:0] io_r_resp_data_2,
  output [41:0] io_r_resp_data_3,
  output [41:0] io_r_resp_data_4,
  output [41:0] io_r_resp_data_5,
  output [41:0] io_r_resp_data_6,
  output [41:0] io_r_resp_data_7,
  output        io_w_req_ready,
  input         io_w_req_valid,
  input  [8:0]  io_w_req_bits_setIdx,
  input  [41:0] io_w_req_bits_data_0,
  input  [41:0] io_w_req_bits_data_1,
  input  [41:0] io_w_req_bits_data_2,
  input  [41:0] io_w_req_bits_data_3,
  input  [41:0] io_w_req_bits_data_4,
  input  [41:0] io_w_req_bits_data_5,
  input  [41:0] io_w_req_bits_data_6,
  input  [41:0] io_w_req_bits_data_7,
  input  [7:0]  io_w_req_bits_waymask,
  input  [9:0]  boreChildrenBd_bore_addr,
  input  [9:0]  boreChildrenBd_bore_addr_rd,
  input  [83:0] boreChildrenBd_bore_wdata,
  input  [3:0]  boreChildrenBd_bore_wmask,
  input         boreChildrenBd_bore_re,
  input         boreChildrenBd_bore_we,
  output [83:0] boreChildrenBd_bore_rdata,
  input         boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_selectedOH,
  input  [2:0]  boreChildrenBd_bore_array,
  input  [9:0]  boreChildrenBd_bore_1_addr,
  input  [9:0]  boreChildrenBd_bore_1_addr_rd,
  input  [83:0] boreChildrenBd_bore_1_wdata,
  input  [3:0]  boreChildrenBd_bore_1_wmask,
  input         boreChildrenBd_bore_1_re,
  input         boreChildrenBd_bore_1_we,
  output [83:0] boreChildrenBd_bore_1_rdata,
  input         boreChildrenBd_bore_1_ack,
  input         boreChildrenBd_bore_1_selectedOH,
  input  [2:0]  boreChildrenBd_bore_1_array,
  input  [9:0]  boreChildrenBd_bore_2_addr,
  input  [9:0]  boreChildrenBd_bore_2_addr_rd,
  input  [83:0] boreChildrenBd_bore_2_wdata,
  input  [3:0]  boreChildrenBd_bore_2_wmask,
  input         boreChildrenBd_bore_2_re,
  input         boreChildrenBd_bore_2_we,
  output [83:0] boreChildrenBd_bore_2_rdata,
  input         boreChildrenBd_bore_2_ack,
  input         boreChildrenBd_bore_2_selectedOH,
  input  [2:0]  boreChildrenBd_bore_2_array,
  input  [9:0]  boreChildrenBd_bore_3_addr,
  input  [9:0]  boreChildrenBd_bore_3_addr_rd,
  input  [83:0] boreChildrenBd_bore_3_wdata,
  input  [3:0]  boreChildrenBd_bore_3_wmask,
  input         boreChildrenBd_bore_3_re,
  input         boreChildrenBd_bore_3_we,
  output [83:0] boreChildrenBd_bore_3_rdata,
  input         boreChildrenBd_bore_3_ack,
  input         boreChildrenBd_bore_3_selectedOH,
  input  [2:0]  boreChildrenBd_bore_3_array,
  input         sigFromSrams_bore_mbist_ram_hold,
  input         sigFromSrams_bore_mbist_ram_bypass,
  input         sigFromSrams_bore_mbist_ram_bp_clken,
  input         sigFromSrams_bore_mbist_ram_aux_clk,
  input         sigFromSrams_bore_mbist_ram_aux_ckbp,
  input         sigFromSrams_bore_mbist_ram_mcp_hold,
  input         sigFromSrams_bore_mbist_cgen,
  input         sigFromSrams_bore_1_mbist_ram_hold,
  input         sigFromSrams_bore_1_mbist_ram_bypass,
  input         sigFromSrams_bore_1_mbist_ram_bp_clken,
  input         sigFromSrams_bore_1_mbist_ram_aux_clk,
  input         sigFromSrams_bore_1_mbist_ram_aux_ckbp,
  input         sigFromSrams_bore_1_mbist_ram_mcp_hold,
  input         sigFromSrams_bore_1_mbist_cgen,
  input         sigFromSrams_bore_2_mbist_ram_hold,
  input         sigFromSrams_bore_2_mbist_ram_bypass,
  input         sigFromSrams_bore_2_mbist_ram_bp_clken,
  input         sigFromSrams_bore_2_mbist_ram_aux_clk,
  input         sigFromSrams_bore_2_mbist_ram_aux_ckbp,
  input         sigFromSrams_bore_2_mbist_ram_mcp_hold,
  input         sigFromSrams_bore_2_mbist_cgen,
  input         sigFromSrams_bore_3_mbist_ram_hold,
  input         sigFromSrams_bore_3_mbist_ram_bypass,
  input         sigFromSrams_bore_3_mbist_ram_bp_clken,
  input         sigFromSrams_bore_3_mbist_ram_aux_clk,
  input         sigFromSrams_bore_3_mbist_ram_aux_ckbp,
  input         sigFromSrams_bore_3_mbist_ram_mcp_hold,
  input         sigFromSrams_bore_3_mbist_cgen
);

  wire [20:0] _array_0_1_1_io_r_resp_data_0;
  wire [20:0] _array_0_1_1_io_r_resp_data_1;
  wire [20:0] _array_0_1_1_io_r_resp_data_2;
  wire [20:0] _array_0_1_1_io_r_resp_data_3;
  wire [20:0] _array_0_1_0_io_r_resp_data_0;
  wire [20:0] _array_0_1_0_io_r_resp_data_1;
  wire [20:0] _array_0_1_0_io_r_resp_data_2;
  wire [20:0] _array_0_1_0_io_r_resp_data_3;
  wire [20:0] _array_0_0_1_io_r_resp_data_0;
  wire [20:0] _array_0_0_1_io_r_resp_data_1;
  wire [20:0] _array_0_0_1_io_r_resp_data_2;
  wire [20:0] _array_0_0_1_io_r_resp_data_3;
  wire [20:0] _array_0_0_0_io_r_resp_data_0;
  wire [20:0] _array_0_0_0_io_r_resp_data_1;
  wire [20:0] _array_0_0_0_io_r_resp_data_2;
  wire [20:0] _array_0_0_0_io_r_resp_data_3;
  SRAMTemplate_136 array_0_0_0 (
    .clock                           (clock),
    .reset                           (reset),
    .io_r_req_ready                  (io_r_req_ready),
    .io_r_req_valid                  (io_r_req_valid),
    .io_r_req_bits_setIdx            (io_r_req_bits_setIdx),
    .io_r_resp_data_0                (_array_0_0_0_io_r_resp_data_0),
    .io_r_resp_data_1                (_array_0_0_0_io_r_resp_data_1),
    .io_r_resp_data_2                (_array_0_0_0_io_r_resp_data_2),
    .io_r_resp_data_3                (_array_0_0_0_io_r_resp_data_3),
    .io_w_req_valid                  (io_w_req_valid),
    .io_w_req_bits_setIdx            (io_w_req_bits_setIdx),
    .io_w_req_bits_data_0            (io_w_req_bits_data_0[20:0]),
    .io_w_req_bits_data_1            (io_w_req_bits_data_1[20:0]),
    .io_w_req_bits_data_2            (io_w_req_bits_data_2[20:0]),
    .io_w_req_bits_data_3            (io_w_req_bits_data_3[20:0]),
    .io_w_req_bits_waymask           (io_w_req_bits_waymask[3:0]),
    .io_broadcast_mbist_ram_hold     (sigFromSrams_bore_mbist_ram_hold),
    .io_broadcast_mbist_ram_bypass   (sigFromSrams_bore_mbist_ram_bypass),
    .io_broadcast_mbist_ram_bp_clken (sigFromSrams_bore_mbist_ram_bp_clken),
    .io_broadcast_mbist_ram_aux_clk  (sigFromSrams_bore_mbist_ram_aux_clk),
    .io_broadcast_mbist_ram_aux_ckbp (sigFromSrams_bore_mbist_ram_aux_ckbp),
    .io_broadcast_mbist_ram_mcp_hold (sigFromSrams_bore_mbist_ram_mcp_hold),
    .io_broadcast_mbist_cgen         (sigFromSrams_bore_mbist_cgen),
    .io_broadcast_sramCtl_MCR        (2'h0),
    .io_broadcast_sramCtl_MCW        (2'h0),
    .io_broadcast_sramCtl_RTSEL      (2'h0),
    .io_broadcast_sramCtl_WTSEL      (2'h0),
    .io_broadcast_sramCtl_RCT        (2'h0),
    .io_broadcast_sramCtl_WCT        (2'h0),
    .io_broadcast_sramCtl_KP         (3'h0),
    .boreChildrenBd_bore_addr        (boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_addr_rd     (boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_wdata       (boreChildrenBd_bore_wdata),
    .boreChildrenBd_bore_wmask       (boreChildrenBd_bore_wmask),
    .boreChildrenBd_bore_re          (boreChildrenBd_bore_re),
    .boreChildrenBd_bore_we          (boreChildrenBd_bore_we),
    .boreChildrenBd_bore_rdata       (boreChildrenBd_bore_rdata),
    .boreChildrenBd_bore_ack         (boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_selectedOH  (boreChildrenBd_bore_selectedOH),
    .boreChildrenBd_bore_array       (boreChildrenBd_bore_array)
  );
  SRAMTemplate_136 array_0_0_1 (
    .clock                           (clock),
    .reset                           (reset),
    .io_r_req_ready                  (/* unused */),
    .io_r_req_valid                  (io_r_req_valid),
    .io_r_req_bits_setIdx            (io_r_req_bits_setIdx),
    .io_r_resp_data_0                (_array_0_0_1_io_r_resp_data_0),
    .io_r_resp_data_1                (_array_0_0_1_io_r_resp_data_1),
    .io_r_resp_data_2                (_array_0_0_1_io_r_resp_data_2),
    .io_r_resp_data_3                (_array_0_0_1_io_r_resp_data_3),
    .io_w_req_valid                  (io_w_req_valid),
    .io_w_req_bits_setIdx            (io_w_req_bits_setIdx),
    .io_w_req_bits_data_0            (io_w_req_bits_data_0[41:21]),
    .io_w_req_bits_data_1            (io_w_req_bits_data_1[41:21]),
    .io_w_req_bits_data_2            (io_w_req_bits_data_2[41:21]),
    .io_w_req_bits_data_3            (io_w_req_bits_data_3[41:21]),
    .io_w_req_bits_waymask           (io_w_req_bits_waymask[3:0]),
    .io_broadcast_mbist_ram_hold     (sigFromSrams_bore_1_mbist_ram_hold),
    .io_broadcast_mbist_ram_bypass   (sigFromSrams_bore_1_mbist_ram_bypass),
    .io_broadcast_mbist_ram_bp_clken (sigFromSrams_bore_1_mbist_ram_bp_clken),
    .io_broadcast_mbist_ram_aux_clk  (sigFromSrams_bore_1_mbist_ram_aux_clk),
    .io_broadcast_mbist_ram_aux_ckbp (sigFromSrams_bore_1_mbist_ram_aux_ckbp),
    .io_broadcast_mbist_ram_mcp_hold (sigFromSrams_bore_1_mbist_ram_mcp_hold),
    .io_broadcast_mbist_cgen         (sigFromSrams_bore_1_mbist_cgen),
    .io_broadcast_sramCtl_MCR        (2'h0),
    .io_broadcast_sramCtl_MCW        (2'h0),
    .io_broadcast_sramCtl_RTSEL      (2'h0),
    .io_broadcast_sramCtl_WTSEL      (2'h0),
    .io_broadcast_sramCtl_RCT        (2'h0),
    .io_broadcast_sramCtl_WCT        (2'h0),
    .io_broadcast_sramCtl_KP         (3'h0),
    .boreChildrenBd_bore_addr        (boreChildrenBd_bore_1_addr),
    .boreChildrenBd_bore_addr_rd     (boreChildrenBd_bore_1_addr_rd),
    .boreChildrenBd_bore_wdata       (boreChildrenBd_bore_1_wdata),
    .boreChildrenBd_bore_wmask       (boreChildrenBd_bore_1_wmask),
    .boreChildrenBd_bore_re          (boreChildrenBd_bore_1_re),
    .boreChildrenBd_bore_we          (boreChildrenBd_bore_1_we),
    .boreChildrenBd_bore_rdata       (boreChildrenBd_bore_1_rdata),
    .boreChildrenBd_bore_ack         (boreChildrenBd_bore_1_ack),
    .boreChildrenBd_bore_selectedOH  (boreChildrenBd_bore_1_selectedOH),
    .boreChildrenBd_bore_array       (boreChildrenBd_bore_1_array)
  );
  SRAMTemplate_136 array_0_1_0 (
    .clock                           (clock),
    .reset                           (reset),
    .io_r_req_ready                  (/* unused */),
    .io_r_req_valid                  (io_r_req_valid),
    .io_r_req_bits_setIdx            (io_r_req_bits_setIdx),
    .io_r_resp_data_0                (_array_0_1_0_io_r_resp_data_0),
    .io_r_resp_data_1                (_array_0_1_0_io_r_resp_data_1),
    .io_r_resp_data_2                (_array_0_1_0_io_r_resp_data_2),
    .io_r_resp_data_3                (_array_0_1_0_io_r_resp_data_3),
    .io_w_req_valid                  (io_w_req_valid),
    .io_w_req_bits_setIdx            (io_w_req_bits_setIdx),
    .io_w_req_bits_data_0            (io_w_req_bits_data_4[20:0]),
    .io_w_req_bits_data_1            (io_w_req_bits_data_5[20:0]),
    .io_w_req_bits_data_2            (io_w_req_bits_data_6[20:0]),
    .io_w_req_bits_data_3            (io_w_req_bits_data_7[20:0]),
    .io_w_req_bits_waymask           (io_w_req_bits_waymask[7:4]),
    .io_broadcast_mbist_ram_hold     (sigFromSrams_bore_2_mbist_ram_hold),
    .io_broadcast_mbist_ram_bypass   (sigFromSrams_bore_2_mbist_ram_bypass),
    .io_broadcast_mbist_ram_bp_clken (sigFromSrams_bore_2_mbist_ram_bp_clken),
    .io_broadcast_mbist_ram_aux_clk  (sigFromSrams_bore_2_mbist_ram_aux_clk),
    .io_broadcast_mbist_ram_aux_ckbp (sigFromSrams_bore_2_mbist_ram_aux_ckbp),
    .io_broadcast_mbist_ram_mcp_hold (sigFromSrams_bore_2_mbist_ram_mcp_hold),
    .io_broadcast_mbist_cgen         (sigFromSrams_bore_2_mbist_cgen),
    .io_broadcast_sramCtl_MCR        (2'h0),
    .io_broadcast_sramCtl_MCW        (2'h0),
    .io_broadcast_sramCtl_RTSEL      (2'h0),
    .io_broadcast_sramCtl_WTSEL      (2'h0),
    .io_broadcast_sramCtl_RCT        (2'h0),
    .io_broadcast_sramCtl_WCT        (2'h0),
    .io_broadcast_sramCtl_KP         (3'h0),
    .boreChildrenBd_bore_addr        (boreChildrenBd_bore_2_addr),
    .boreChildrenBd_bore_addr_rd     (boreChildrenBd_bore_2_addr_rd),
    .boreChildrenBd_bore_wdata       (boreChildrenBd_bore_2_wdata),
    .boreChildrenBd_bore_wmask       (boreChildrenBd_bore_2_wmask),
    .boreChildrenBd_bore_re          (boreChildrenBd_bore_2_re),
    .boreChildrenBd_bore_we          (boreChildrenBd_bore_2_we),
    .boreChildrenBd_bore_rdata       (boreChildrenBd_bore_2_rdata),
    .boreChildrenBd_bore_ack         (boreChildrenBd_bore_2_ack),
    .boreChildrenBd_bore_selectedOH  (boreChildrenBd_bore_2_selectedOH),
    .boreChildrenBd_bore_array       (boreChildrenBd_bore_2_array)
  );
  SRAMTemplate_136 array_0_1_1 (
    .clock                           (clock),
    .reset                           (reset),
    .io_r_req_ready                  (/* unused */),
    .io_r_req_valid                  (io_r_req_valid),
    .io_r_req_bits_setIdx            (io_r_req_bits_setIdx),
    .io_r_resp_data_0                (_array_0_1_1_io_r_resp_data_0),
    .io_r_resp_data_1                (_array_0_1_1_io_r_resp_data_1),
    .io_r_resp_data_2                (_array_0_1_1_io_r_resp_data_2),
    .io_r_resp_data_3                (_array_0_1_1_io_r_resp_data_3),
    .io_w_req_valid                  (io_w_req_valid),
    .io_w_req_bits_setIdx            (io_w_req_bits_setIdx),
    .io_w_req_bits_data_0            (io_w_req_bits_data_4[41:21]),
    .io_w_req_bits_data_1            (io_w_req_bits_data_5[41:21]),
    .io_w_req_bits_data_2            (io_w_req_bits_data_6[41:21]),
    .io_w_req_bits_data_3            (io_w_req_bits_data_7[41:21]),
    .io_w_req_bits_waymask           (io_w_req_bits_waymask[7:4]),
    .io_broadcast_mbist_ram_hold     (sigFromSrams_bore_3_mbist_ram_hold),
    .io_broadcast_mbist_ram_bypass   (sigFromSrams_bore_3_mbist_ram_bypass),
    .io_broadcast_mbist_ram_bp_clken (sigFromSrams_bore_3_mbist_ram_bp_clken),
    .io_broadcast_mbist_ram_aux_clk  (sigFromSrams_bore_3_mbist_ram_aux_clk),
    .io_broadcast_mbist_ram_aux_ckbp (sigFromSrams_bore_3_mbist_ram_aux_ckbp),
    .io_broadcast_mbist_ram_mcp_hold (sigFromSrams_bore_3_mbist_ram_mcp_hold),
    .io_broadcast_mbist_cgen         (sigFromSrams_bore_3_mbist_cgen),
    .io_broadcast_sramCtl_MCR        (2'h0),
    .io_broadcast_sramCtl_MCW        (2'h0),
    .io_broadcast_sramCtl_RTSEL      (2'h0),
    .io_broadcast_sramCtl_WTSEL      (2'h0),
    .io_broadcast_sramCtl_RCT        (2'h0),
    .io_broadcast_sramCtl_WCT        (2'h0),
    .io_broadcast_sramCtl_KP         (3'h0),
    .boreChildrenBd_bore_addr        (boreChildrenBd_bore_3_addr),
    .boreChildrenBd_bore_addr_rd     (boreChildrenBd_bore_3_addr_rd),
    .boreChildrenBd_bore_wdata       (boreChildrenBd_bore_3_wdata),
    .boreChildrenBd_bore_wmask       (boreChildrenBd_bore_3_wmask),
    .boreChildrenBd_bore_re          (boreChildrenBd_bore_3_re),
    .boreChildrenBd_bore_we          (boreChildrenBd_bore_3_we),
    .boreChildrenBd_bore_rdata       (boreChildrenBd_bore_3_rdata),
    .boreChildrenBd_bore_ack         (boreChildrenBd_bore_3_ack),
    .boreChildrenBd_bore_selectedOH  (boreChildrenBd_bore_3_selectedOH),
    .boreChildrenBd_bore_array       (boreChildrenBd_bore_3_array)
  );
  assign io_r_resp_data_0 =
    {_array_0_0_1_io_r_resp_data_0, _array_0_0_0_io_r_resp_data_0};
  assign io_r_resp_data_1 =
    {_array_0_0_1_io_r_resp_data_1, _array_0_0_0_io_r_resp_data_1};
  assign io_r_resp_data_2 =
    {_array_0_0_1_io_r_resp_data_2, _array_0_0_0_io_r_resp_data_2};
  assign io_r_resp_data_3 =
    {_array_0_0_1_io_r_resp_data_3, _array_0_0_0_io_r_resp_data_3};
  assign io_r_resp_data_4 =
    {_array_0_1_1_io_r_resp_data_0, _array_0_1_0_io_r_resp_data_0};
  assign io_r_resp_data_5 =
    {_array_0_1_1_io_r_resp_data_1, _array_0_1_0_io_r_resp_data_1};
  assign io_r_resp_data_6 =
    {_array_0_1_1_io_r_resp_data_2, _array_0_1_0_io_r_resp_data_2};
  assign io_r_resp_data_7 =
    {_array_0_1_1_io_r_resp_data_3, _array_0_1_0_io_r_resp_data_3};
  assign io_w_req_ready = 1'h1;
endmodule

