// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SplittedSRAMTemplate_29(
  input          clock,
  input          reset,
  input          io_r_req_valid,
  input  [5:0]   io_r_req_bits_setIdx,
  output [259:0] io_r_resp_data_0_meta,
  output         io_r_resp_data_0_ftb_entry_isCall,
  output         io_r_resp_data_0_ftb_entry_isRet,
  output         io_r_resp_data_0_ftb_entry_isJalr,
  output         io_r_resp_data_0_ftb_entry_valid,
  output [3:0]   io_r_resp_data_0_ftb_entry_brSlots_0_offset,
  output         io_r_resp_data_0_ftb_entry_brSlots_0_sharing,
  output         io_r_resp_data_0_ftb_entry_brSlots_0_valid,
  output [11:0]  io_r_resp_data_0_ftb_entry_brSlots_0_lower,
  output [1:0]   io_r_resp_data_0_ftb_entry_brSlots_0_tarStat,
  output [3:0]   io_r_resp_data_0_ftb_entry_tailSlot_offset,
  output         io_r_resp_data_0_ftb_entry_tailSlot_sharing,
  output         io_r_resp_data_0_ftb_entry_tailSlot_valid,
  output [19:0]  io_r_resp_data_0_ftb_entry_tailSlot_lower,
  output [1:0]   io_r_resp_data_0_ftb_entry_tailSlot_tarStat,
  output [3:0]   io_r_resp_data_0_ftb_entry_pftAddr,
  output         io_r_resp_data_0_ftb_entry_carry,
  output         io_r_resp_data_0_ftb_entry_last_may_be_rvi_call,
  output         io_r_resp_data_0_ftb_entry_strong_bias_0,
  output         io_r_resp_data_0_ftb_entry_strong_bias_1,
  input          io_w_req_valid,
  input  [5:0]   io_w_req_bits_setIdx,
  input  [259:0] io_w_req_bits_data_0_meta,
  input          io_w_req_bits_data_0_ftb_entry_isCall,
  input          io_w_req_bits_data_0_ftb_entry_isRet,
  input          io_w_req_bits_data_0_ftb_entry_isJalr,
  input          io_w_req_bits_data_0_ftb_entry_valid,
  input  [3:0]   io_w_req_bits_data_0_ftb_entry_brSlots_0_offset,
  input          io_w_req_bits_data_0_ftb_entry_brSlots_0_sharing,
  input          io_w_req_bits_data_0_ftb_entry_brSlots_0_valid,
  input  [11:0]  io_w_req_bits_data_0_ftb_entry_brSlots_0_lower,
  input  [1:0]   io_w_req_bits_data_0_ftb_entry_brSlots_0_tarStat,
  input  [3:0]   io_w_req_bits_data_0_ftb_entry_tailSlot_offset,
  input          io_w_req_bits_data_0_ftb_entry_tailSlot_sharing,
  input          io_w_req_bits_data_0_ftb_entry_tailSlot_valid,
  input  [19:0]  io_w_req_bits_data_0_ftb_entry_tailSlot_lower,
  input  [1:0]   io_w_req_bits_data_0_ftb_entry_tailSlot_tarStat,
  input  [3:0]   io_w_req_bits_data_0_ftb_entry_pftAddr,
  input          io_w_req_bits_data_0_ftb_entry_carry,
  input          io_w_req_bits_data_0_ftb_entry_last_may_be_rvi_call,
  input          io_w_req_bits_data_0_ftb_entry_strong_bias_0,
  input          io_w_req_bits_data_0_ftb_entry_strong_bias_1,
  input  [6:0]   boreChildrenBd_bore_addr,
  input  [6:0]   boreChildrenBd_bore_addr_rd,
  input  [159:0] boreChildrenBd_bore_wdata,
  input          boreChildrenBd_bore_wmask,
  input          boreChildrenBd_bore_re,
  input          boreChildrenBd_bore_we,
  output [159:0] boreChildrenBd_bore_rdata,
  input          boreChildrenBd_bore_ack,
  input          boreChildrenBd_bore_selectedOH,
  input  [6:0]   boreChildrenBd_bore_array,
  input  [6:0]   boreChildrenBd_bore_1_addr,
  input  [6:0]   boreChildrenBd_bore_1_addr_rd,
  input  [159:0] boreChildrenBd_bore_1_wdata,
  input          boreChildrenBd_bore_1_wmask,
  input          boreChildrenBd_bore_1_re,
  input          boreChildrenBd_bore_1_we,
  output [159:0] boreChildrenBd_bore_1_rdata,
  input          boreChildrenBd_bore_1_ack,
  input          boreChildrenBd_bore_1_selectedOH,
  input  [6:0]   boreChildrenBd_bore_1_array,
  input          sigFromSrams_bore_mbist_ram_hold,
  input          sigFromSrams_bore_mbist_ram_bypass,
  input          sigFromSrams_bore_mbist_ram_bp_clken,
  input          sigFromSrams_bore_mbist_ram_aux_clk,
  input          sigFromSrams_bore_mbist_ram_aux_ckbp,
  input          sigFromSrams_bore_mbist_ram_mcp_hold,
  input          sigFromSrams_bore_mbist_cgen,
  input          sigFromSrams_bore_1_mbist_ram_hold,
  input          sigFromSrams_bore_1_mbist_ram_bypass,
  input          sigFromSrams_bore_1_mbist_ram_bp_clken,
  input          sigFromSrams_bore_1_mbist_ram_aux_clk,
  input          sigFromSrams_bore_1_mbist_ram_aux_ckbp,
  input          sigFromSrams_bore_1_mbist_ram_mcp_hold,
  input          sigFromSrams_bore_1_mbist_cgen
);

  wire [159:0] _array_0_0_1_io_r_resp_data_0;
  wire [159:0] _array_0_0_0_io_r_resp_data_0;
  SRAMTemplate_78 array_0_0_0 (
    .clock                           (clock),
    .reset                           (reset),
    .io_r_req_valid                  (io_r_req_valid),
    .io_r_req_bits_setIdx            (io_r_req_bits_setIdx),
    .io_r_resp_data_0                (_array_0_0_0_io_r_resp_data_0),
    .io_w_req_valid                  (io_w_req_valid),
    .io_w_req_bits_setIdx            (io_w_req_bits_setIdx),
    .io_w_req_bits_data_0
      ({io_w_req_bits_data_0_meta[99:0],
        io_w_req_bits_data_0_ftb_entry_isCall,
        io_w_req_bits_data_0_ftb_entry_isRet,
        io_w_req_bits_data_0_ftb_entry_isJalr,
        io_w_req_bits_data_0_ftb_entry_valid,
        io_w_req_bits_data_0_ftb_entry_brSlots_0_offset,
        io_w_req_bits_data_0_ftb_entry_brSlots_0_sharing,
        io_w_req_bits_data_0_ftb_entry_brSlots_0_valid,
        io_w_req_bits_data_0_ftb_entry_brSlots_0_lower,
        io_w_req_bits_data_0_ftb_entry_brSlots_0_tarStat,
        io_w_req_bits_data_0_ftb_entry_tailSlot_offset,
        io_w_req_bits_data_0_ftb_entry_tailSlot_sharing,
        io_w_req_bits_data_0_ftb_entry_tailSlot_valid,
        io_w_req_bits_data_0_ftb_entry_tailSlot_lower,
        io_w_req_bits_data_0_ftb_entry_tailSlot_tarStat,
        io_w_req_bits_data_0_ftb_entry_pftAddr,
        io_w_req_bits_data_0_ftb_entry_carry,
        io_w_req_bits_data_0_ftb_entry_last_may_be_rvi_call,
        io_w_req_bits_data_0_ftb_entry_strong_bias_1,
        io_w_req_bits_data_0_ftb_entry_strong_bias_0}),
    .io_broadcast_mbist_ram_hold     (sigFromSrams_bore_mbist_ram_hold),
    .io_broadcast_mbist_ram_bypass   (sigFromSrams_bore_mbist_ram_bypass),
    .io_broadcast_mbist_ram_bp_clken (sigFromSrams_bore_mbist_ram_bp_clken),
    .io_broadcast_mbist_ram_aux_clk  (sigFromSrams_bore_mbist_ram_aux_clk),
    .io_broadcast_mbist_ram_aux_ckbp (sigFromSrams_bore_mbist_ram_aux_ckbp),
    .io_broadcast_mbist_ram_mcp_hold (sigFromSrams_bore_mbist_ram_mcp_hold),
    .io_broadcast_mbist_cgen         (sigFromSrams_bore_mbist_cgen),
    .io_broadcast_sramCtl_MCR        (2'h0),
    .io_broadcast_sramCtl_MCW        (2'h0),
    .io_broadcast_sramCtl_RTSEL      (2'h0),
    .io_broadcast_sramCtl_WTSEL      (2'h0),
    .io_broadcast_sramCtl_RCT        (2'h0),
    .io_broadcast_sramCtl_WCT        (2'h0),
    .io_broadcast_sramCtl_KP         (3'h0),
    .boreChildrenBd_bore_addr        (boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_addr_rd     (boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_wdata       (boreChildrenBd_bore_wdata),
    .boreChildrenBd_bore_wmask       (boreChildrenBd_bore_wmask),
    .boreChildrenBd_bore_re          (boreChildrenBd_bore_re),
    .boreChildrenBd_bore_we          (boreChildrenBd_bore_we),
    .boreChildrenBd_bore_rdata       (boreChildrenBd_bore_rdata),
    .boreChildrenBd_bore_ack         (boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_selectedOH  (boreChildrenBd_bore_selectedOH),
    .boreChildrenBd_bore_array       (boreChildrenBd_bore_array)
  );
  SRAMTemplate_78 array_0_0_1 (
    .clock                           (clock),
    .reset                           (reset),
    .io_r_req_valid                  (io_r_req_valid),
    .io_r_req_bits_setIdx            (io_r_req_bits_setIdx),
    .io_r_resp_data_0                (_array_0_0_1_io_r_resp_data_0),
    .io_w_req_valid                  (io_w_req_valid),
    .io_w_req_bits_setIdx            (io_w_req_bits_setIdx),
    .io_w_req_bits_data_0            (io_w_req_bits_data_0_meta[259:100]),
    .io_broadcast_mbist_ram_hold     (sigFromSrams_bore_1_mbist_ram_hold),
    .io_broadcast_mbist_ram_bypass   (sigFromSrams_bore_1_mbist_ram_bypass),
    .io_broadcast_mbist_ram_bp_clken (sigFromSrams_bore_1_mbist_ram_bp_clken),
    .io_broadcast_mbist_ram_aux_clk  (sigFromSrams_bore_1_mbist_ram_aux_clk),
    .io_broadcast_mbist_ram_aux_ckbp (sigFromSrams_bore_1_mbist_ram_aux_ckbp),
    .io_broadcast_mbist_ram_mcp_hold (sigFromSrams_bore_1_mbist_ram_mcp_hold),
    .io_broadcast_mbist_cgen         (sigFromSrams_bore_1_mbist_cgen),
    .io_broadcast_sramCtl_MCR        (2'h0),
    .io_broadcast_sramCtl_MCW        (2'h0),
    .io_broadcast_sramCtl_RTSEL      (2'h0),
    .io_broadcast_sramCtl_WTSEL      (2'h0),
    .io_broadcast_sramCtl_RCT        (2'h0),
    .io_broadcast_sramCtl_WCT        (2'h0),
    .io_broadcast_sramCtl_KP         (3'h0),
    .boreChildrenBd_bore_addr        (boreChildrenBd_bore_1_addr),
    .boreChildrenBd_bore_addr_rd     (boreChildrenBd_bore_1_addr_rd),
    .boreChildrenBd_bore_wdata       (boreChildrenBd_bore_1_wdata),
    .boreChildrenBd_bore_wmask       (boreChildrenBd_bore_1_wmask),
    .boreChildrenBd_bore_re          (boreChildrenBd_bore_1_re),
    .boreChildrenBd_bore_we          (boreChildrenBd_bore_1_we),
    .boreChildrenBd_bore_rdata       (boreChildrenBd_bore_1_rdata),
    .boreChildrenBd_bore_ack         (boreChildrenBd_bore_1_ack),
    .boreChildrenBd_bore_selectedOH  (boreChildrenBd_bore_1_selectedOH),
    .boreChildrenBd_bore_array       (boreChildrenBd_bore_1_array)
  );
  assign io_r_resp_data_0_meta =
    {_array_0_0_1_io_r_resp_data_0, _array_0_0_0_io_r_resp_data_0[159:60]};
  assign io_r_resp_data_0_ftb_entry_isCall = _array_0_0_0_io_r_resp_data_0[59];
  assign io_r_resp_data_0_ftb_entry_isRet = _array_0_0_0_io_r_resp_data_0[58];
  assign io_r_resp_data_0_ftb_entry_isJalr = _array_0_0_0_io_r_resp_data_0[57];
  assign io_r_resp_data_0_ftb_entry_valid = _array_0_0_0_io_r_resp_data_0[56];
  assign io_r_resp_data_0_ftb_entry_brSlots_0_offset =
    _array_0_0_0_io_r_resp_data_0[55:52];
  assign io_r_resp_data_0_ftb_entry_brSlots_0_sharing = _array_0_0_0_io_r_resp_data_0[51];
  assign io_r_resp_data_0_ftb_entry_brSlots_0_valid = _array_0_0_0_io_r_resp_data_0[50];
  assign io_r_resp_data_0_ftb_entry_brSlots_0_lower =
    _array_0_0_0_io_r_resp_data_0[49:38];
  assign io_r_resp_data_0_ftb_entry_brSlots_0_tarStat =
    _array_0_0_0_io_r_resp_data_0[37:36];
  assign io_r_resp_data_0_ftb_entry_tailSlot_offset =
    _array_0_0_0_io_r_resp_data_0[35:32];
  assign io_r_resp_data_0_ftb_entry_tailSlot_sharing = _array_0_0_0_io_r_resp_data_0[31];
  assign io_r_resp_data_0_ftb_entry_tailSlot_valid = _array_0_0_0_io_r_resp_data_0[30];
  assign io_r_resp_data_0_ftb_entry_tailSlot_lower = _array_0_0_0_io_r_resp_data_0[29:10];
  assign io_r_resp_data_0_ftb_entry_tailSlot_tarStat = _array_0_0_0_io_r_resp_data_0[9:8];
  assign io_r_resp_data_0_ftb_entry_pftAddr = _array_0_0_0_io_r_resp_data_0[7:4];
  assign io_r_resp_data_0_ftb_entry_carry = _array_0_0_0_io_r_resp_data_0[3];
  assign io_r_resp_data_0_ftb_entry_last_may_be_rvi_call =
    _array_0_0_0_io_r_resp_data_0[2];
  assign io_r_resp_data_0_ftb_entry_strong_bias_0 = _array_0_0_0_io_r_resp_data_0[0];
  assign io_r_resp_data_0_ftb_entry_strong_bias_1 = _array_0_0_0_io_r_resp_data_0[1];
endmodule

