// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SRAMTemplate_78(
  input          clock,
  input          reset,
  input          io_r_req_valid,
  input  [5:0]   io_r_req_bits_setIdx,
  output [159:0] io_r_resp_data_0,
  input          io_w_req_valid,
  input  [5:0]   io_w_req_bits_setIdx,
  input  [159:0] io_w_req_bits_data_0,
  input          io_broadcast_mbist_ram_hold,
  input          io_broadcast_mbist_ram_bypass,
  input          io_broadcast_mbist_ram_bp_clken,
  input          io_broadcast_mbist_ram_aux_clk,
  input          io_broadcast_mbist_ram_aux_ckbp,
  input          io_broadcast_mbist_ram_mcp_hold,
  input          io_broadcast_mbist_cgen,
  input  [1:0]   io_broadcast_sramCtl_MCR,
  input  [1:0]   io_broadcast_sramCtl_MCW,
  input  [1:0]   io_broadcast_sramCtl_RTSEL,
  input  [1:0]   io_broadcast_sramCtl_WTSEL,
  input  [1:0]   io_broadcast_sramCtl_RCT,
  input  [1:0]   io_broadcast_sramCtl_WCT,
  input  [2:0]   io_broadcast_sramCtl_KP,
  input  [6:0]   boreChildrenBd_bore_addr,
  input  [6:0]   boreChildrenBd_bore_addr_rd,
  input  [159:0] boreChildrenBd_bore_wdata,
  input          boreChildrenBd_bore_wmask,
  input          boreChildrenBd_bore_re,
  input          boreChildrenBd_bore_we,
  output [159:0] boreChildrenBd_bore_rdata,
  input          boreChildrenBd_bore_ack,
  input          boreChildrenBd_bore_selectedOH,
  input  [6:0]   boreChildrenBd_bore_array
);

  wire [159:0] _array_R0_data;
  wire         _wcg_out_clock;
  wire         _rcg_out_clock;
  wire [6:0]   mbistBd_addr = boreChildrenBd_bore_addr;
  wire [6:0]   mbistBd_addr_rd = boreChildrenBd_bore_addr_rd;
  wire [159:0] mbistBd_wdata = boreChildrenBd_bore_wdata;
  wire         mbistBd_wmask = boreChildrenBd_bore_wmask;
  wire         mbistBd_re = boreChildrenBd_bore_re;
  wire         mbistBd_we = boreChildrenBd_bore_we;
  wire         mbistBd_ack = boreChildrenBd_bore_ack;
  wire         mbistWmask = boreChildrenBd_bore_selectedOH;
  wire [6:0]   mbistBd_array = boreChildrenBd_bore_array;
  wire         wckEn = mbistBd_ack ? mbistBd_we : io_w_req_valid;
  wire         rckEn = mbistBd_ack ? mbistBd_re : io_r_req_valid;
  reg          respReg;
  reg  [63:0]  bypass_wdata_lfsr;
  wire         bypass_mask_need_check = io_r_req_valid & io_w_req_valid;
  reg          bypass_mask_need_check_reg_last_REG;
  reg  [5:0]   bypass_mask_waddr_reg;
  reg  [5:0]   bypass_mask_raddr_reg;
  reg  [159:0] rdataReg;
  wire [159:0] mbistBd_rdata = rdataReg;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      respReg <= 1'h0;
      bypass_wdata_lfsr <= 64'h1234567887654321;
      bypass_mask_need_check_reg_last_REG <= 1'h0;
    end
    else begin
      respReg <= rckEn;
      if (bypass_wdata_lfsr == 64'h0)
        bypass_wdata_lfsr <= 64'h1;
      else
        bypass_wdata_lfsr <=
          {bypass_wdata_lfsr[0] ^ bypass_wdata_lfsr[1] ^ bypass_wdata_lfsr[3]
             ^ bypass_wdata_lfsr[4],
           bypass_wdata_lfsr[63:1]};
      bypass_mask_need_check_reg_last_REG <= bypass_mask_need_check;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (bypass_mask_need_check) begin
      bypass_mask_waddr_reg <= io_w_req_bits_setIdx;
      bypass_mask_raddr_reg <= io_r_req_bits_setIdx;
    end
    if (respReg)
      rdataReg <= _array_R0_data;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:7];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;
        end
        respReg = _RANDOM[3'h0][0];
        bypass_wdata_lfsr = {_RANDOM[3'h0][31:1], _RANDOM[3'h1], _RANDOM[3'h2][0]};
        bypass_mask_need_check_reg_last_REG = _RANDOM[3'h2][1];
        bypass_mask_waddr_reg = _RANDOM[3'h2][7:2];
        bypass_mask_raddr_reg = _RANDOM[3'h2][13:8];
        rdataReg =
          {_RANDOM[3'h2][31:15],
           _RANDOM[3'h3],
           _RANDOM[3'h4],
           _RANDOM[3'h5],
           _RANDOM[3'h6],
           _RANDOM[3'h7][14:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        respReg = 1'h0;
        bypass_wdata_lfsr = 64'h1234567887654321;
        bypass_mask_need_check_reg_last_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MbistClockGateCell rcg (
    .clock         (clock),
    .mbist_writeen (1'h0),
    .mbist_readen  (rckEn),
    .mbist_req     (mbistBd_ack),
    .E             (rckEn),
    .dft_cgen      (io_broadcast_mbist_cgen),
    .out_clock     (_rcg_out_clock)
  );
  MbistClockGateCell wcg (
    .clock         (clock),
    .mbist_writeen (wckEn),
    .mbist_readen  (1'h0),
    .mbist_req     (mbistBd_ack),
    .E             (wckEn),
    .dft_cgen      (io_broadcast_mbist_cgen),
    .out_clock     (_wcg_out_clock)
  );
  sram_array_2p64x160m160s1h0l1b_ftq array (
    .mbist_dft_ram_bypass   (io_broadcast_mbist_ram_bypass),
    .mbist_dft_ram_bp_clken (io_broadcast_mbist_ram_bp_clken),
    .sramCtl_MCR            (io_broadcast_sramCtl_MCR),
    .sramCtl_MCW            (io_broadcast_sramCtl_MCW),
    .sramCtl_RTSEL          (io_broadcast_sramCtl_RTSEL),
    .sramCtl_WTSEL          (io_broadcast_sramCtl_WTSEL),
    .sramCtl_RCT            (io_broadcast_sramCtl_RCT),
    .sramCtl_WCT            (io_broadcast_sramCtl_WCT),
    .sramCtl_KP             (io_broadcast_sramCtl_KP),
    .R0_clk                 (_rcg_out_clock),
    .R0_addr                (mbistBd_ack ? mbistBd_addr_rd[5:0] : io_r_req_bits_setIdx),
    .R0_en                  (rckEn),
    .R0_data                (_array_R0_data),
    .W0_clk                 (_wcg_out_clock),
    .W0_addr                (mbistBd_ack ? mbistBd_addr[5:0] : io_w_req_bits_setIdx),
    .W0_en                  (wckEn & ~io_broadcast_mbist_ram_hold),
    .W0_data                (mbistBd_ack ? mbistBd_wdata : io_w_req_bits_data_0)
  );
  assign io_r_resp_data_0 =
    bypass_mask_need_check_reg_last_REG & bypass_mask_waddr_reg == bypass_mask_raddr_reg
      ? {96'h0, bypass_wdata_lfsr}
      : _array_R0_data;
  assign boreChildrenBd_bore_rdata = mbistBd_rdata;
endmodule

