// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SRAMTemplate_136(
  input         clock,
  input         reset,
  output        io_r_req_ready,
  input         io_r_req_valid,
  input  [8:0]  io_r_req_bits_setIdx,
  output [20:0] io_r_resp_data_0,
  output [20:0] io_r_resp_data_1,
  output [20:0] io_r_resp_data_2,
  output [20:0] io_r_resp_data_3,
  input         io_w_req_valid,
  input  [8:0]  io_w_req_bits_setIdx,
  input  [20:0] io_w_req_bits_data_0,
  input  [20:0] io_w_req_bits_data_1,
  input  [20:0] io_w_req_bits_data_2,
  input  [20:0] io_w_req_bits_data_3,
  input  [3:0]  io_w_req_bits_waymask,
  input         io_broadcast_mbist_ram_hold,
  input         io_broadcast_mbist_ram_bypass,
  input         io_broadcast_mbist_ram_bp_clken,
  input         io_broadcast_mbist_ram_aux_clk,
  input         io_broadcast_mbist_ram_aux_ckbp,
  input         io_broadcast_mbist_ram_mcp_hold,
  input         io_broadcast_mbist_cgen,
  input  [1:0]  io_broadcast_sramCtl_MCR,
  input  [1:0]  io_broadcast_sramCtl_MCW,
  input  [1:0]  io_broadcast_sramCtl_RTSEL,
  input  [1:0]  io_broadcast_sramCtl_WTSEL,
  input  [1:0]  io_broadcast_sramCtl_RCT,
  input  [1:0]  io_broadcast_sramCtl_WCT,
  input  [2:0]  io_broadcast_sramCtl_KP,
  input  [9:0]  boreChildrenBd_bore_addr,
  input  [9:0]  boreChildrenBd_bore_addr_rd,
  input  [83:0] boreChildrenBd_bore_wdata,
  input  [3:0]  boreChildrenBd_bore_wmask,
  input         boreChildrenBd_bore_re,
  input         boreChildrenBd_bore_we,
  output [83:0] boreChildrenBd_bore_rdata,
  input         boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_selectedOH,
  input  [2:0]  boreChildrenBd_bore_array
);

  wire [83:0] _array_RW0_rdata;
  wire [9:0]  mbistBd_addr = boreChildrenBd_bore_addr;
  wire [9:0]  mbistBd_addr_rd = boreChildrenBd_bore_addr_rd;
  wire [83:0] mbistBd_wdata = boreChildrenBd_bore_wdata;
  wire [3:0]  mbistBd_wmask = boreChildrenBd_bore_wmask;
  wire        mbistBd_re = boreChildrenBd_bore_re;
  wire        mbistBd_we = boreChildrenBd_bore_we;
  wire        mbistBd_ack = boreChildrenBd_bore_ack;
  wire        mbistBd_selectedOH = boreChildrenBd_bore_selectedOH;
  wire [2:0]  mbistBd_array = boreChildrenBd_bore_array;
  wire        rckEn = mbistBd_ack ? mbistBd_re : ~io_w_req_valid & io_r_req_valid;
  wire        _GEN =
    (mbistBd_ack ? mbistBd_we : io_w_req_valid) & ~io_broadcast_mbist_ram_hold;
  reg         respReg;
  reg  [83:0] rdataReg;
  wire [83:0] mbistBd_rdata = rdataReg;
  always @(posedge clock or posedge reset) begin
    if (reset)
      respReg <= 1'h0;
    else
      respReg <= rckEn;
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (respReg)
      rdataReg <= _array_RW0_rdata;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:11];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hC; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        respReg = _RANDOM[4'h0][0];
        rdataReg =
          {_RANDOM[4'h8][31:24], _RANDOM[4'h9], _RANDOM[4'hA], _RANDOM[4'hB][11:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset)
        respReg = 1'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  sram_array_1p512x84m21s1h0l1b_l2_tag array (
    .mbist_dft_ram_bypass   (io_broadcast_mbist_ram_bypass),
    .mbist_dft_ram_bp_clken (io_broadcast_mbist_ram_bp_clken),
    .sramCtl_MCR            (io_broadcast_sramCtl_MCR),
    .sramCtl_MCW            (io_broadcast_sramCtl_MCW),
    .sramCtl_RTSEL          (io_broadcast_sramCtl_RTSEL),
    .sramCtl_WTSEL          (io_broadcast_sramCtl_WTSEL),
    .sramCtl_RCT            (io_broadcast_sramCtl_RCT),
    .sramCtl_WCT            (io_broadcast_sramCtl_WCT),
    .sramCtl_KP             (io_broadcast_sramCtl_KP),
    .RW0_clk                (clock),
    .RW0_addr
      (mbistBd_ack
         ? mbistBd_addr_rd[8:0]
         : _GEN ? io_w_req_bits_setIdx : io_r_req_bits_setIdx),
    .RW0_en                 (_GEN | rckEn),
    .RW0_wmode              (_GEN),
    .RW0_wmask
      (mbistBd_ack ? {4{mbistBd_selectedOH}} & mbistBd_wmask : io_w_req_bits_waymask),
    .RW0_wdata
      (mbistBd_ack
         ? mbistBd_wdata
         : {io_w_req_bits_data_3,
            io_w_req_bits_data_2,
            io_w_req_bits_data_1,
            io_w_req_bits_data_0}),
    .RW0_rdata              (_array_RW0_rdata)
  );
  assign io_r_req_ready = ~io_w_req_valid;
  assign io_r_resp_data_0 = _array_RW0_rdata[20:0];
  assign io_r_resp_data_1 = _array_RW0_rdata[41:21];
  assign io_r_resp_data_2 = _array_RW0_rdata[62:42];
  assign io_r_resp_data_3 = _array_RW0_rdata[83:63];
  assign boreChildrenBd_bore_rdata = mbistBd_rdata;
endmodule

