// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module SRAMTemplate_64(
  input         clock,
  input         reset,
  input         io_r_req_valid,
  input  [7:0]  io_r_req_bits_setIdx,
  output [1:0]  io_r_resp_data_0,
  output [1:0]  io_r_resp_data_1,
  output [1:0]  io_r_resp_data_2,
  output [1:0]  io_r_resp_data_3,
  output [1:0]  io_r_resp_data_4,
  output [1:0]  io_r_resp_data_5,
  output [1:0]  io_r_resp_data_6,
  output [1:0]  io_r_resp_data_7,
  input         io_w_req_valid,
  input  [7:0]  io_w_req_bits_setIdx,
  input  [1:0]  io_w_req_bits_data_0,
  input  [1:0]  io_w_req_bits_data_1,
  input  [1:0]  io_w_req_bits_data_2,
  input  [1:0]  io_w_req_bits_data_3,
  input  [1:0]  io_w_req_bits_data_4,
  input  [1:0]  io_w_req_bits_data_5,
  input  [1:0]  io_w_req_bits_data_6,
  input  [1:0]  io_w_req_bits_data_7,
  input  [7:0]  io_w_req_bits_waymask,
  input         io_broadcast_mbist_ram_hold,
  input         io_broadcast_mbist_ram_bypass,
  input         io_broadcast_mbist_ram_bp_clken,
  input         io_broadcast_mbist_ram_aux_clk,
  input         io_broadcast_mbist_ram_aux_ckbp,
  input         io_broadcast_mbist_ram_mcp_hold,
  input         io_broadcast_mbist_cgen,
  input  [1:0]  io_broadcast_sramCtl_MCR,
  input  [1:0]  io_broadcast_sramCtl_MCW,
  input  [1:0]  io_broadcast_sramCtl_RTSEL,
  input  [1:0]  io_broadcast_sramCtl_WTSEL,
  input  [1:0]  io_broadcast_sramCtl_RCT,
  input  [1:0]  io_broadcast_sramCtl_WCT,
  input  [2:0]  io_broadcast_sramCtl_KP,
  input  [8:0]  boreChildrenBd_bore_addr,
  input  [8:0]  boreChildrenBd_bore_addr_rd,
  input  [15:0] boreChildrenBd_bore_wdata,
  input  [7:0]  boreChildrenBd_bore_wmask,
  input         boreChildrenBd_bore_re,
  input         boreChildrenBd_bore_we,
  output [15:0] boreChildrenBd_bore_rdata,
  input         boreChildrenBd_bore_ack,
  input         boreChildrenBd_bore_selectedOH,
  input  [6:0]  boreChildrenBd_bore_array
);

  wire [15:0] _array_R0_data;
  wire        _wcg_out_clock;
  wire        _rcg_out_clock;
  wire [8:0]  mbistBd_addr = boreChildrenBd_bore_addr;
  wire [8:0]  mbistBd_addr_rd = boreChildrenBd_bore_addr_rd;
  wire [15:0] mbistBd_wdata = boreChildrenBd_bore_wdata;
  wire [7:0]  mbistBd_wmask = boreChildrenBd_bore_wmask;
  wire        mbistBd_re = boreChildrenBd_bore_re;
  wire        mbistBd_we = boreChildrenBd_bore_we;
  wire        mbistBd_ack = boreChildrenBd_bore_ack;
  wire        mbistBd_selectedOH = boreChildrenBd_bore_selectedOH;
  wire [6:0]  mbistBd_array = boreChildrenBd_bore_array;
  wire        wckEn = mbistBd_ack ? mbistBd_we : io_w_req_valid;
  wire        rckEn = mbistBd_ack ? mbistBd_re : io_r_req_valid;
  reg         respReg;
  reg  [1:0]  bypass_wdata_r_0;
  reg  [1:0]  bypass_wdata_r_1;
  reg  [1:0]  bypass_wdata_r_2;
  reg  [1:0]  bypass_wdata_r_3;
  reg  [1:0]  bypass_wdata_r_4;
  reg  [1:0]  bypass_wdata_r_5;
  reg  [1:0]  bypass_wdata_r_6;
  reg  [1:0]  bypass_wdata_r_7;
  wire        bypass_mask_need_check = io_r_req_valid & io_w_req_valid;
  reg         bypass_mask_need_check_reg_last_REG;
  reg  [7:0]  bypass_mask_waddr_reg;
  reg  [7:0]  bypass_mask_raddr_reg;
  reg  [7:0]  bypass_mask_wmask_reg;
  wire [7:0]  bypass_mask =
    {8{bypass_mask_need_check_reg_last_REG
         & bypass_mask_waddr_reg == bypass_mask_raddr_reg}} & bypass_mask_wmask_reg;
  wire [1:0]  mem_rdata_0 = bypass_mask[0] ? bypass_wdata_r_0 : _array_R0_data[1:0];
  wire [1:0]  mem_rdata_1 = bypass_mask[1] ? bypass_wdata_r_1 : _array_R0_data[3:2];
  wire [1:0]  mem_rdata_2 = bypass_mask[2] ? bypass_wdata_r_2 : _array_R0_data[5:4];
  wire [1:0]  mem_rdata_3 = bypass_mask[3] ? bypass_wdata_r_3 : _array_R0_data[7:6];
  wire [1:0]  mem_rdata_4 = bypass_mask[4] ? bypass_wdata_r_4 : _array_R0_data[9:8];
  wire [1:0]  mem_rdata_5 = bypass_mask[5] ? bypass_wdata_r_5 : _array_R0_data[11:10];
  wire [1:0]  mem_rdata_6 = bypass_mask[6] ? bypass_wdata_r_6 : _array_R0_data[13:12];
  wire [1:0]  mem_rdata_7 = bypass_mask[7] ? bypass_wdata_r_7 : _array_R0_data[15:14];
  reg         rdata_last_REG;
  reg  [1:0]  rdata_hold_data_0;
  reg  [1:0]  rdata_hold_data_1;
  reg  [1:0]  rdata_hold_data_2;
  reg  [1:0]  rdata_hold_data_3;
  reg  [1:0]  rdata_hold_data_4;
  reg  [1:0]  rdata_hold_data_5;
  reg  [1:0]  rdata_hold_data_6;
  reg  [1:0]  rdata_hold_data_7;
  reg  [15:0] rdataReg;
  wire [15:0] mbistBd_rdata = rdataReg;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      respReg <= 1'h0;
      bypass_mask_need_check_reg_last_REG <= 1'h0;
      rdata_last_REG <= 1'h0;
    end
    else begin
      respReg <= rckEn;
      bypass_mask_need_check_reg_last_REG <= bypass_mask_need_check;
      rdata_last_REG <= io_r_req_valid;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io_w_req_valid & io_r_req_valid) begin
      bypass_wdata_r_0 <= io_w_req_bits_data_0;
      bypass_wdata_r_1 <= io_w_req_bits_data_1;
      bypass_wdata_r_2 <= io_w_req_bits_data_2;
      bypass_wdata_r_3 <= io_w_req_bits_data_3;
      bypass_wdata_r_4 <= io_w_req_bits_data_4;
      bypass_wdata_r_5 <= io_w_req_bits_data_5;
      bypass_wdata_r_6 <= io_w_req_bits_data_6;
      bypass_wdata_r_7 <= io_w_req_bits_data_7;
    end
    if (bypass_mask_need_check) begin
      bypass_mask_waddr_reg <= io_w_req_bits_setIdx;
      bypass_mask_raddr_reg <= io_r_req_bits_setIdx;
      bypass_mask_wmask_reg <= io_w_req_bits_waymask;
    end
    if (rdata_last_REG) begin
      rdata_hold_data_0 <= mem_rdata_0;
      rdata_hold_data_1 <= mem_rdata_1;
      rdata_hold_data_2 <= mem_rdata_2;
      rdata_hold_data_3 <= mem_rdata_3;
      rdata_hold_data_4 <= mem_rdata_4;
      rdata_hold_data_5 <= mem_rdata_5;
      rdata_hold_data_6 <= mem_rdata_6;
      rdata_hold_data_7 <= mem_rdata_7;
    end
    if (respReg)
      rdataReg <= _array_R0_data;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        respReg = _RANDOM[2'h0][0];
        bypass_wdata_r_0 = _RANDOM[2'h0][2:1];
        bypass_wdata_r_1 = _RANDOM[2'h0][4:3];
        bypass_wdata_r_2 = _RANDOM[2'h0][6:5];
        bypass_wdata_r_3 = _RANDOM[2'h0][8:7];
        bypass_wdata_r_4 = _RANDOM[2'h0][10:9];
        bypass_wdata_r_5 = _RANDOM[2'h0][12:11];
        bypass_wdata_r_6 = _RANDOM[2'h0][14:13];
        bypass_wdata_r_7 = _RANDOM[2'h0][16:15];
        bypass_mask_need_check_reg_last_REG = _RANDOM[2'h0][17];
        bypass_mask_waddr_reg = _RANDOM[2'h0][25:18];
        bypass_mask_raddr_reg = {_RANDOM[2'h0][31:26], _RANDOM[2'h1][1:0]};
        bypass_mask_wmask_reg = _RANDOM[2'h1][9:2];
        rdata_last_REG = _RANDOM[2'h1][10];
        rdata_hold_data_0 = _RANDOM[2'h1][12:11];
        rdata_hold_data_1 = _RANDOM[2'h1][14:13];
        rdata_hold_data_2 = _RANDOM[2'h1][16:15];
        rdata_hold_data_3 = _RANDOM[2'h1][18:17];
        rdata_hold_data_4 = _RANDOM[2'h1][20:19];
        rdata_hold_data_5 = _RANDOM[2'h1][22:21];
        rdata_hold_data_6 = _RANDOM[2'h1][24:23];
        rdata_hold_data_7 = _RANDOM[2'h1][26:25];
        rdataReg = {_RANDOM[2'h1][31:27], _RANDOM[2'h2][10:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        respReg = 1'h0;
        bypass_mask_need_check_reg_last_REG = 1'h0;
        rdata_last_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MbistClockGateCell rcg (
    .clock         (clock),
    .mbist_writeen (1'h0),
    .mbist_readen  (rckEn),
    .mbist_req     (mbistBd_ack),
    .E             (rckEn),
    .dft_cgen      (io_broadcast_mbist_cgen),
    .out_clock     (_rcg_out_clock)
  );
  MbistClockGateCell wcg (
    .clock         (clock),
    .mbist_writeen (wckEn),
    .mbist_readen  (1'h0),
    .mbist_req     (mbistBd_ack),
    .E             (wckEn),
    .dft_cgen      (io_broadcast_mbist_cgen),
    .out_clock     (_wcg_out_clock)
  );
  sram_array_2p256x16m2s1h0l1b_bp_tage_bt array (
    .mbist_dft_ram_bypass   (io_broadcast_mbist_ram_bypass),
    .mbist_dft_ram_bp_clken (io_broadcast_mbist_ram_bp_clken),
    .sramCtl_MCR            (io_broadcast_sramCtl_MCR),
    .sramCtl_MCW            (io_broadcast_sramCtl_MCW),
    .sramCtl_RTSEL          (io_broadcast_sramCtl_RTSEL),
    .sramCtl_WTSEL          (io_broadcast_sramCtl_WTSEL),
    .sramCtl_RCT            (io_broadcast_sramCtl_RCT),
    .sramCtl_WCT            (io_broadcast_sramCtl_WCT),
    .sramCtl_KP             (io_broadcast_sramCtl_KP),
    .R0_clk                 (_rcg_out_clock),
    .R0_addr                (mbistBd_ack ? mbistBd_addr_rd[7:0] : io_r_req_bits_setIdx),
    .R0_en                  (rckEn),
    .R0_data                (_array_R0_data),
    .W0_clk                 (_wcg_out_clock),
    .W0_addr                (mbistBd_ack ? mbistBd_addr[7:0] : io_w_req_bits_setIdx),
    .W0_en                  (wckEn & ~io_broadcast_mbist_ram_hold),
    .W0_data
      (mbistBd_ack
         ? mbistBd_wdata
         : {io_w_req_bits_data_7,
            io_w_req_bits_data_6,
            io_w_req_bits_data_5,
            io_w_req_bits_data_4,
            io_w_req_bits_data_3,
            io_w_req_bits_data_2,
            io_w_req_bits_data_1,
            io_w_req_bits_data_0}),
    .W0_mask
      (mbistBd_ack ? {8{mbistBd_selectedOH}} & mbistBd_wmask : io_w_req_bits_waymask)
  );
  assign io_r_resp_data_0 = rdata_last_REG ? mem_rdata_0 : rdata_hold_data_0;
  assign io_r_resp_data_1 = rdata_last_REG ? mem_rdata_1 : rdata_hold_data_1;
  assign io_r_resp_data_2 = rdata_last_REG ? mem_rdata_2 : rdata_hold_data_2;
  assign io_r_resp_data_3 = rdata_last_REG ? mem_rdata_3 : rdata_hold_data_3;
  assign io_r_resp_data_4 = rdata_last_REG ? mem_rdata_4 : rdata_hold_data_4;
  assign io_r_resp_data_5 = rdata_last_REG ? mem_rdata_5 : rdata_hold_data_5;
  assign io_r_resp_data_6 = rdata_last_REG ? mem_rdata_6 : rdata_hold_data_6;
  assign io_r_resp_data_7 = rdata_last_REG ? mem_rdata_7 : rdata_hold_data_7;
  assign boreChildrenBd_bore_rdata = mbistBd_rdata;
endmodule

